arr_wake = [
    "Bom dia Muchachos!",
    "Bom dia seus Conas de Sabão!",
    "Bom dia seus Ginos-Bolhas!",
    "Bom dia Jiripoias!",
    "Bom dia lindos!",
    "Bom dia Caralho!",
    "Bom dia Gente",
    "Bom dia Palhaços",
    "Bom dia seus Caras-de-Cu",
    "Bom dia Humanos Nojentos",
    "Bom dia para quem trabalha",
    "Buenos dias Matosinos",
    "Buenos dias Muchachos",
    "Guten Morgen",
    "Bom dia seus Porcos",
    "Bom dia seus Seres com corpos e necessidades básicas",
    "Acordei Rabujento",
    "Bom dia seus javardos",
    "Bom dia humanos",
    "Bom dia Cabeças de Melão",
    "Bom dia seus Cara de Amendoim",
    "Bom dia caralhos",
    "Bom dia sobreviventes",
    "Bom dia alegados furtadores de malas",
    "Bom dia, eu odeio-vos",
    "Bom dia suas Abéculas",
    "Bom dia suas Abentesmas",
    "Bom dia suas Alimárias",
    "Bom dia seus Andrajosos",
    "Bom dia seus Cacóstomos",
    "Bom dia seus Tatibitates",
    "Bom dia, todos vocês cheiram a cholé",
    "Bom dia Badamecos",
    "Bom dia bois",
    "Bom dia seus borra-botas",
    "Bom dia seus cabeças de alho xoxo",
    "Bom dia camelos",
    "Bom dia seus Caras-de-Cu à paisana",
    "Bom dia Canalhas",
    "Bom dia seus Desmancha Prazeres",
    "Bom dia Desbocados",
    "Bom dia seus foleiros",
    "Bom dia Falhados",
    "Bom dia Flausinos",
    "Bom dia Gosmas",
    "Bom dia seus Idiotas",
    "Bom dia seus Imbecis",
    "Bom dia seus lambe-conas",
    "Bom dia Larápios",
    "Bom dia Morcões",
    "Bom dia Malucos",
    "Bom dia seus Malacuecos",
    "Bom dia Malandragem",
    "Bom dia seus Mastronços",
    "Bom dia seus meia-leca",
    "Bom dia merdosos",
    "Bom dia Larápios",
    "Bom dia molengos",
    "Bom dia seus Miseráveis",
    "Bom dia Mulas",
    "Bom dia suas Nódoas",
    "Bom dia Nabos",
    "Bom dia suas Nulidades",
    "Bom dia seus Nojentos",
    "Bom dia Otários",
    "Bom dia Palermas",
    "Bom dia seus parvalhões",
    "Bom dia Patetas",
    "Bom dia Pirosos",
    "Bom dia seus peida-gaxoxas",
    "Bom dia seus piolhosos",
    "Bom dia Pelintras",
    "Bom dia Palhaços",
    "Bom dia Pacóvios",
    "Bom dia seus pobres de espírito",
    "Bom dia Patinhos Feios",
    "Bom dia seus panhonhas",
    "Bom dia Parasitas",
    "Bom dia Ranhosos",
    "Bom dia seus reles",
    "Bom dia Sacanas",
    "Bom dia Tarados",
    "Bom dia Trombalazanas",
    "Bom dia Trapaceiros",
    "Bom dia Ursos",
    "Bom dia Vagabundos",
    "Bom dia Vendidos",
]
