arr_fortune = [
    "é perfeita para te focares no teu bem-estar físico através de atividades. Considera adicionar mais prota à tua dieta e presta atenção na área genital. Alongamentos suaves ou yoga podem ajudar a aliviar qualquer rigidez ou desconforto",
    ", com a Lua se movendo para Touro, traz um senso de praticidade ao teu mundo emocional. Hoje, você pode se encontrar refletindo sobre a segurança financeira em relação às suas relações",
    "as comunicações e planos que estavam em banho-maria vão começar a fluir. Aproveita para esclarecer mal-entendidos e retomar projetos que estavam parados",
    "vejo uma morte iminente, envolta nas sombras de um acidente de asfixia auto-erótica",
    "as estrelas indicam que a probabilidade do Jaime te cuspir na cara não é zero",
    "vejo, nas linhas invisíveis da energia cósmica, que algo do servidor está prestes a ser papado por ti. O destino está a favor",
    "cuidado, pois o karma se aproxima, trazendo sérios problemas com a lei. O futuro não é claro, mas exige atenção",
    "vislumbro que a probabilidade de o Chrys te propor um jantar platónico não é 0",
    "poderás acordar um novo fetish sexual ao ver TV, cuidado com os canais que escolhes (TLC)",
    ", ah, uma visão clara se forma: uma mosca será uma companhia inesperada, surgindo na tua sopa. Presta atenção aos pequenos detalhes",
    "novas oportunidades de negócios surgirão em tua porta, especialmente aquelas ligadas ao mundo peculiar dos onlyfeet",
    "vejo uma possibilidade de perda, talvez um centímetro, cuidados com as tesouras, podem ser as responsáveis pelo corte do destino",
    "nos caminhos do amor, uma alma gémea está prestes a cruzar o teu caminho, trazendo consigo uma história que marcará a tua vida",
    "sinto nas correntes energéticas que, em breve, serás raptado por forças cósmicas. Serás levado a um encontro de outros mundos. Prepara-te para o probe anal!",
    "o destino está prestes a revelar um novo caminho: siga sua intuição e o futuro será tão brilhante como a careca do Toirão",
    "as cartas revelam que uma proposta para um menage está a caminho. No entanto, não te apresses a aceitar, confia no que te digo!",
    "os ventos do universo dizem que o caminho do JECS irá conduzir-te a um novo destino, um que transformará a tua visão e te conduzirá para novos horizontes comunas",
    "vejo nos meus cristais que em breve sentirás a dor de um pequeno obstáculo no teu caminho. Prepare-te para pisares um lego",
    "as estrelas sussurram que a AnaCoração, em breve, escreverá palavras sobre ti, uma fanfic que refletirá a sua admiração",
    "parece que as energias estão conectadas. Prevejo um pensamento que se formará na minha mente sobre ti, uma sessão de masturbação só tu e eu ;) ",
    "o tarô mostra que se aproximam momentos de atenção carinhosa. Um novo encontro está no horizonte... Queres ir num date?",
    ", não há maneira bonita de dizer isto, vais apanhar uma narsa de todo o tamanho",
    "vejo que um LSD será oferecido a ti. O conselho é claro: não aceites esse presente",
    "os astros preveem que serás tocado por um inusitado evento com um ananás do Mercadona. Algo inusitado acontecerá... é melhor estar alerta!",
    "devias jogar no euromilhões, as probabilidades de ganhar são baixas, mas imagina que se ganhares dava a puta história que era o 'Jardas disse-me para jogar e zumbas ganhei'",
    "deves evitar pessoas vestidas de vermelho. Acredita, não queres saber o porquê",
    "o teu tio vai-te convidar para mostrar um spot todo fixe, depois baza e deixa-te sozinho. Passado um bocado vem uma manada de antílopes ou o caralho, entretanto o teu pai salva-te mas morre no processo",
    "as cartas revelam uma sombra de traição no teu futuro... Cuidado, pode ser alguém em quem confias cegamente",
    "os astros estão alinhados para o amor! Uma paixão avassaladora está a caminho, e talvez esteja mais perto do que pensas...",
    "uma energia especial a envolve o teu destino. O que te espera é um amor inesperado... será que me apaixonarás, ou será outro caminho a seguir? A bola de cristal não mente!",
    "as cartas mostram sinais de alerta para a tua saúde. Cuida-te, pois é grande a probabilidade de seres o paciente zero de uma nova variante. O nome dela... não vais gostar de saber",
    "o vento traz uma mudança para a tua carreira... as estrelas indicam que uma perda de emprego está no teu horizonte. Este será um momento de transformação",
    "os astros mostram que o amor surgirá onde menos esperas neste servidor... Uma paixão inesperada está a caminho",
    "sinto uma forte energia, uma visão que promete algo profundo e inesperado... um sonho ardente e molhado com alguém deste servidor",
    "a sorte parece estar a sorrir para ti! Vejo nas cartas um encontro inesperado com uma fortuna, se estiveres atento aos sinais",
    "as estrelas sorriem para os aventureiros e os audaciosos! O One Piece vai ser encontrado por ti!",
    "não deixes a indecisão tomar conta do teu destino. Age com firmeza, sem esperar por ordens, pois o tempo não espera por ninguém",
    "uma relação está forte, mas é necessário equilíbrio. Evita exigir demais, encontra soluções criativas para resolver os obstáculos",
    "os céus pedem para cultivares uma atitude mais discreta e prudente. O dia trará poucos avanços devido à falta de apoio e tempo, por isso é melhor esperar pacientemente",
    "os astros sugerem que cultives a tua energia javarda. Quando menos esperares, será necessário usar essa força para seguir em frente",
    "todas as movimentações no campo afetivo favorecem os teus interesses. A tua opinião será essencial e trará resultados poderosos. Não hesites em intervir",
    "a sorte está a teu favor em dias de ternura e afetos. Tudo se alinha perfeitamente, mas os astros alertam: não alteres os teus planos nem deixes tarefas por cumprir",
    "há previsão para boas cavalgadas. Continua a seguir o teu caminho, sem desviar-te dos teus compromissos",
    "vejo um grande encontro sexual, o melhor da tua vida, onde tudo se alinha de forma especial. Os astros indicam: evita recusar ofertas de qualquer tipo",
    "a sabedoria dos astros aconselha-te a cumprir rigorosamente os teus compromissos. Move-te com sensatez, e o sucesso será teu aliado",
    "os astros sugerem que deves deixar os receios de lado e buscar esclarecimentos sobre aquilo que está oculto. Com essa coragem, encontrarás o caminho para melhorias",
    "um encontro familiar que pode ultrapassar limites aproxima-se, mas lembra-te: não tens culpa no cartório. Um dia tenso em que a paciência será a tua maior aliada",
    ", nos caminhos do prazer, os astros falam de uma experiência sexual que poderá ultrapassar os teus limites. Não te assustes, pois algumas surpresas agradáveis podem surgir",
    "temos indicadores financeiros favoráveis. Há boas possibilidades de aumento profissional ou até mesmo de encontrar uma fortuna",
    "a tua energia está em alta, mas lembra-te de não atropelares os outros pelo caminho. Uma conversa inesperada pode trazer boas surpresas",
    ", apesar de alguns contratempos, confia que estás no caminho certo. Uma oportunidade financeira pode surgir onde menos esperas",
    "aproveita para comunicar os teus pensamentos, mas certifica-te de que estás a ouvir tanto quanto falas. Alguém próximo pode precisar do teu apoio",
    "a tua intuição está apurada, usa-a para tomar decisões importantes. Não ignores os sinais do teu corpo; descansa se for necessário",
    "a tua libido vai estar em altas. Cuidado para não fazeres algo que te arrependas ou então vai que é tua",
    "prevejo perigo sério. Cuidado com facas e tesouras para não ficares igual ao Rui e perderes os teus cms",
    "as atenções estão viradas para ti, mas usa o teu charme com sabedoria. Um amigo pode pedir-te conselhos valiosos, sê generoso",
    "as atenções estão viradas para ti. Um amigo pode te fazer uma oferta indecente, mas nunca se sabe",
    "não te stresses com os detalhes e confia no processo. Uma conversa profunda pode trazer clareza sobre algo que te preocupa",
    "vais encontrar formas de equilibrar trabalho e prazer. Um convite inesperado pode alegrar o teu dia",
    "a tua intensidade natural está ao rubro. Usa essa energia para te focares nos teus objetivos, mas evita discussões desnecessárias. O amor pode surpreender-te hoje",
    "o espírito de aventura chama por ti. Se puderes, explora algo novo ;) . A tua honestidade será apreciada, mas lembra-te de ser gentil",
    "a tua dedicação ao trabalho pode trazer frutos. Contudo, não te esqueças de passar tempo com quem amas. Pequenos gestos de carinho farão toda a diferença.",
    "a tua criatividade está em alta. Encontra maneiras de expressar as tuas ideias únicas. Uma ligação especial pode aprofundar-se através de uma conversa sincera",
    "a tua sensibilidade está apurada. Usa-a para fortalecer as tuas relações, mas protege-te de energias negativas",
    "vejo uma sombra do passado a chegar às tuas DMs…",
    "o coração está prestes a encontrar a paz que tanto procura. Confie no fluxo da vida",
    "a sorte está sorrindo para você, mas lembre-se: sua felicidade depende das escolhas que faz agora",
    "um encontro inesperado trará mudanças significativas. Preste atenção aos sinais ao seu redor",
    "o vento do futuro sopra suavemente em sua direção, trazendo consigo oportunidades que você jamais imaginou",
    "prevejo uma grande transformação, e ela vai exigir de você coragem para abraçar o novo",
    "os astros indicam que você encontrará algo que procurava há muito tempo",
    "o ciclo da vida está prestes a se fechar, mas não se assuste: isso é apenas a preparação para o próximo capítulo",
    "vejo uma paixão intensa, mas ela virá de uma forma que você nunca imaginou... esteja preparada para o inesperado",
    "o desejo está no ar, e ele vai bater à sua porta mais cedo do que você pensa. Deixe-se levar, mas cuidado com os riscos",
    "um segredo ardente será revelado, e ele vai fazer seu coração acelerar de uma forma que você não vai resistir",
    "o universo conspira para que você experimente algo que há muito tempo deseja, mas esteja ciente de que as consequências serão tão intensas quanto o prazer",
    "vai surgir a tentação de se envolver numa situação perigosa... mas será impossível resistir ao calor dessa atração",
    "destino vai dar uma chance de explorar uma paixão proibida. A escolha será sua, mas cuidado... o jogo pode ser viciante",
    "um olhar quente e cheio de promessas vai fazer seu coração bater mais forte. Não tente fugir, pois o destino é irresistível",
    ", o que está por vir será uma mistura de prazer e mistério, mas lembre-se: o amor e o desejo às vezes se disfarçam de desafios",
    "vejo em seus caminhos uma atração avassaladora que pode levar você a lugares que você nunca pensou em ir. Permita-se, mas sem arrependimentos",
    "algo quente está prestes a acontecer, e a única certeza que posso dar é que você não vai querer que acabe",
    "os astros indicam que algo te será tirado. Não resistas, pois a perda faz parte do teu caminho, mas prepara-te para a dor que virá",
    "vejo uma sombra a pairar sobre a tua saúde. Cuida-te, pois o teu corpo pode começar a dar sinais que não podes ignorar",
    "os ventos não estão a teu favor. Uma grande frustração no trabalho está por vir, e o reconhecimento que esperas pode nunca acontecer",
    "os astros mostram que a tua confiança será posta à prova. Alguém próximo poderá te decepcionar, e a dor dessa traição será mais profunda do que imaginas",
    "as estrelas falam de um afastamento inesperado. Alguém que consideras importante pode desaparecer da tua vida, deixando-te com um vazio difícil de preencher",
    "o teu caminho afetivo está nublado. O amor que esperas pode não surgir tão cedo, e até mesmo as relações atuais podem ser testadas de forma amarga",
    "há uma energia de caos nos teus projetos. Se não tomares cuidado, o fracasso estará mais próximo do que pensas, prepara-te para enfrentar obstáculos difíceis",
    "as cartas revelam uma desilusão financeira. Um investimento pode falhar, e será necessário encontrar forças para recomeçar do zero",
    "os astros indicam que o teu equilíbrio emocional será abalado. Algo ou alguém te fará questionar o que consideravas seguro, e a inquietação será difícil de controlar",
    "vejo sinais de solidão. Momentos de isolamento podem surgir, e será um desafio encontrar consolo nas pequenas coisas",
    "a energia é de uma sensação de impotência. Algo que tentas há muito tempo pode não dar frutos, e a frustração será difícil de evitar",
    "as estrelas revelam que a tua paciência será testada. Um conflito inevitável pode surgir em tua vida, e será difícil encontrar uma solução sem danos",
    "o teu tio vai-te convidar para mostrar um spot todo fixe, depois baza e deixa-te sozinho. Passado um bocado vem uma manada de antílopes ou o caralho, entretanto o teu pai salva-te mas morre no processo",
    "não prevejo nada para ti porque tou sem vontade",
    "podes ir para o caralhinho"
]