arr_fortune = [
    "é perfeita para te focares no teu bem-estar físico através de atividades. Considera adicionar mais prota à tua dieta e presta atenção na área genital. Alongamentos suaves ou yoga podem ajudar a aliviar qualquer rigidez ou desconforto",
    "com a Lua se movendo para Touro, traz um senso de praticidade para o seu mundo emocional. Hoje, você pode se encontrar refletindo sobre a segurança financeira em relação às suas relações.",
    "as comunicações e planos que estavam em banho-maria vão começar a fluir. Aproveita para esclarecer mal-entendidos e retomar projetos que estavam parados",
    "prevejo que vás morrer num acidente de asfixia auto-erótica",
    "a probabilidade do Jaime te cuspir na cara esta semana não é 0",
    "prevejo que vais papar alguém do servidor",
    "vais ter problemas sérios com a lei",
    "a probabilidade do Chrys te propor um jantar platónico não é 0",
    "poderás acordar um novo fetish sexual ao ver TV, cuidado com os canais que escolhes (TLC)",
    "irás ter um mosca na sopa",
    "novas oportunidades de negócio aparecerão à porta, onlyfeet",
    "existe a possibilidade de perderes 1cm, cuidado com tesouras",
    "irás conhecer o amor da tua vida",
    "prevejo que vais ser raptado por aliens vão-te fazer probe anal",
    "O destino está prestes a revelar um novo caminho: siga sua intuição e o futuro será tão brilhante como a careca do Toirão",
    "irás receber uma proposta para um menage. Não aceites, confia!!!",
    "o JECS vai-te converter para o comunismo",
    "vais pisar um lego",
    "a Ana irá escrever uma fanfic sobre ti",
    "prevejo que eu me masturbe a pensar em ti ;)",
    "prevejo que se vais ter atenção amorosa. Já agora, queres ir num date?",
    "vais apanhar uma narsa de todo tamanho",
    "vão-te oferecer LSD. Não aceites!!!",
    "vais ser vítima dum ananás do mercadona",
    "devias jogar no euromilhões, as probabilidades de ganhar são baixas, mas imagina que se ganhares dava a puta história que era o 'Jardas disse-me para jogar e zumbas ganhei'",
    "deves evitar pessoas vestidas de vermelho. Acredita, não queres saber o porquê",
    "vejo uma traição inesperada... talvez de alguém em quem confias cegamente",
    "o amor está no ar! Vais apaixonar-te, e pode ser mais perto do que imaginas",
    "há algo especial no teu caminho. Vais apaixonar-te por mim? A bola de cristal não mente!",
    "atenção à saúde... há grandes possibilidades de seres o paciente zero duma nova variante, e não vais gostar do nome dela",
    "vais perder o emprego",
    "vais apaixonar-te pela pessoa que menos esperas deste sv",
    "vais ter um sonho molhado com alguém deste sv",
    "vais encontrar uma fortuna, anda atento",
    "vais encontrar o One Piece",
    "o teu tio vai-te convidar para mostrar um spot todo fixe, depois baza e deixa-te sozinho. Passado um bocado vem uma manada de antílopes ou o caralho, entretanto o teu pai salva-te mas morre no processo",
    ""
]