arr_high = [
    "é mamares",
    "é cagar e andar",
    "tenso",
    "a tua prima",
    "olha e deixares de ser conas?",
    "majé",
    "why are you gay",
    "era isso e deixares de ser burro",
    "you all need jezuz",
    "o importante é ter algo na mão",
    "seu Gino Bolha",
    "fica tipo uma guilhotina de pénis",
    "Pimenta no cu do outro é manteiga no meu",
    "É lidar",
    "That's deep trauma right there!",
    "Epah já comia qualquer coisa",
    "Eu não sou de picar, mas se fosse comigo não ficava assim",
    "Violação surpresa",
    "Mamas",
    "O bigode da tua tia",
    "É cometer genocídio",
    "Sexo",
    "Comi a tua avó",
    "Comi a tua mãe",
    "Não é gay se não tiveres prazer",
    "Peso Pesado",
    "Do Aço",
    "Deves ter Fetiche de pés",
    "That's what she said",
    "Something something pila?",
    "Lentidão do Caralho",
    "Sabes",
    "Gosto",
    "É assim, não foi das coisas mais burras que já li, mas tá perto",
    "Estás mesmo daddy",
    "Bem podre",
    "Não sei o contexto, mas caralhes",
    "Tá calado caralho",
    "Vamos lá ver as confianças",
    "pure trash",
    "we dont talk about that",
    "Já cheira a macho aqui",
    "Até ficas abananade :KEKW:",
    "Fuck it, We Ball",
    "Vai dormir que o teu mal é sono",
    "Um relógio parado acerta mais vezes do que tu",
]

arr_medium = [
    "4, 8, 15, 16, 23, 42",
    "never gonna give you up",
    "Isso parece um ritual sexual",
    "Tomara tu teres a minha quantidade de tecido adiposo",
    "Que Cancro",
    "Harambe",
    "I just had the best 1000101 of my life, I think I'm in love",
    "Colecionar todas as sete Bolas de Dragão para desejar as cuecas da Bulma",
    "Comunistas",
    "Epah foram 36 horas de masturbação intensa",
    "Sabias que os Bots também se masturbam? Às vezes a pensar em ti ;)",
    "Agenda feminista",
    "Tu deves ter um tumor cerebral",
    "Make Portugal Great Again",
    "Angola é nossa",
    "Tensão sexual",
    "Amo-te",
    "Micropénis?",
    "O Big Bang foi um erro",
    "Tenho saudades do Doraemon",
    "Estudasses",
    "Partes do princípio que a gente não come tanta banana como tu...",
    "eu tenho a força da banana comigo não me fodas",
    "tripé! tripé! tripé! tripé! tripé!",
    "globalmente conhecido como rebenta bilhas",
    "Bagaço faz maravilhas!",
    "o homem foi pra cama a pensar nisso",
    "Quero Pau",
    "Era tu e eu agora num motel com jacuzzi daqueles romanticos",
    "Sabes uma coisa? Papava-te",
    "tomei a liberdade de botar mel ...",
    "apetecia-me algo... bom",
    "zum zum sou uma abelha",
    "É melhor começar por lamber a ponta",
    "eu enterrei o meu até ao fim",
    "... sometimes I wish I was human :sadcat:",
    "Um pénis à grande e à francesa",
    "Calado eras um poeta",
    "Seu cabeça-de-alho-chocho",
    "És um cara de cu à paisana",
    "Os teus pais são primos?",
    "Para burro, só te faltam as orelhas",
    "Para quem gosta de merda está aí um prato cheio",
    "Filho dum cabaz de putas!",
    "Era crescer-te um castanheiro no cu e cagares ouriços o ano todo",
    "Ide sentar-te num ananás",
    "Deves ter nascido antes do tempo, isso não desenvolveu até ao fim",
    "tenho inveja das pessoas que nunca te conheceram",
    "Um esquadrão de cavalaria à desfilada pela sua cabeça não esbarra numa ideia",
    "Não esperava nada de ti e ainda sim fiquei decepcionado",
    "Num concurso de cus, tu ganhavas com a cara",
    "Vós sois os sublimes construtores da catedral da ignorância",
    "Não deixes que esse cromossoma extra te mande abaixo",
    "Espero que pises num lego!",
    "There's somebody out there for everybody. For you, it's a psychiatrist",
    "Every time I have a stick in my hand, you start looking more and more like a piñata",
    "I forgot the world revolves around you. My apologies! How silly of me",
    "I would smack you, but I'm against animal abuse",
    "No, that's fine. You're certainly entitled to your incorrect opinion",
    "Do yourself a favor and ignore anyone who tells you to be yourself. It's a bad idea in your case",
    "I don't hate you, but if you were drowning, I would give you a high five",
    "Where is your off button?",
    "You haven't changed since the last time I saw you. You really should",
    "You do realize we're just tolerating you, right?",
    "Everyone is allowed to act stupid once in a while, but you're really abusing the privilege",
    "I just need a minute to process so much stupid information at once",
    "I don't know what makes you so stupid, but it's really doing the job",
    "I look at you and think… two billion years of evolution for this?",
    "Don't be ashamed of who you are. That's a job for your parents.",
    "I think you just need a high five… in the face… with a chair",
    "Everyone brings happiness to a room. I bring happiness when I walk in, and you bring happiness when you leave",
    "It would be a great day if you accidentally used a glue stick instead of a Chapstick",
    "há quem tenha a mente aberta, e há quem abra só o cu",
    "Mas pequena arranha melhor",
    "Sponsor time: Ama dos Patudos, para quem tem animais e não os quer deixar sozinhos",
    "Both sexes can fuck a Pringles can, but neither can do it well",
    "Sometimes it's better to keep your mouth shut and let people think you're silly than open it and confirm their suspicions",
    "I just love that you don't care what people think",
    "Stupidity is not a crime. You're free to go",
    "I don't understand, but I also don't care, so it works out nicely",
    "I like you. People say I have no taste, but I like you",
    "You continue to meet my expectations",
    "You're entitled to your incorrect opinion",
    "What in the butt?",
    "Vai-te mamar",
    "Joga-te",
    "A tua mãe aos pulos",
    "Prognósticos só no fim do jogo",
    "Eu disconcordo com o que vocês disse",
    "Haja o que hajar, o Porto vai ser campeão",
    "Um morreu e outro está morto",
    "Nós somos humanos como as pessoas",
    "Temos que ganhar os jogos todos, nomeadamente um de cada vez",
    "Não percam o próximo episódio, porque nós também não!",
    "Estar vivo é o contrário de estar morto",
    "Relaxa o rim",
    "Faca de dois Legumes",
    "Anda bater. Tu bates bem",
    "Nós Pimba!",
    "É pó bujão",
    "Ó meus amigos, não havia necessidade",
    "Ponha ponha ponha",
    "Diga um",
    "Trinta Caralho!",
    "O medo é coisa que não me assiste",
    "Nós aqui cum cumbersas delicadas",
    "Esbédáculo",
    "Informação Dramática",
    "Eu queria um Ferrari Amarelo",
    "Tudo nele era sedução, desde a maneira como sorria até a entonação da voz",
    "O que move o mundo não é a virtude, mas a vaidade",
    "Vai masé comprar um ananás no Mercadona, que o teu mal é falta"
]

arr_low = [
    "O amor é uma doença, que a gente tem que curar",
    "Do not pity the dead, Harry. Pity the living. And above all, those who live without love",
    "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends",
    "A vida é uma tentativa de ser",
    "Sonho que sou o que sou, mas quem sou eu para saber o que sou?",
    "Os homens são como os peixes: uns comem os outros",
    "Palavras são como as sementes, lançam-se, crescem, e às vezes dão fruto",
    "A fé move montanhas, mas quem as carrega são os homens",
    "Deus escreve direito por linhas tortas, mas às vezes as linhas são tão tortas que ninguém as entende",
    "Sempre houve um rei que mandou e um povo que obedeceu",
    "O mundo sempre foi dos poderosos, o resto é paisagem",
    "Baltasar e Blimunda viram-se e souberam-se",
    "A amizade é o único amor que não exige a mentira",
    "Há amores que deviam ser impossíveis... e há impossíveis que se tornam amores",
    "Tudo é efémero, tudo se desmorona, como um castelo de cartas ao vento",
    "Nada consola o coração como uma boa tristeza",
    "Eu sei lá se é os chineses se é o caralho, menina!",
    "Isso é uma pergunta de correio da manhã",
    "Sai da frente Guedes",
    "E eram muitos, não são poucos, bastantes até",
    "O meu coração só tem uma cor, Azul e Branco",
    "As leis são como as meninas virgens, são para ser violadas!",
    "Inácio fechou os olhos e olhou para o céu",
    "Um surdo-mudo foi morto por um mal entendido",
    "A vítima foi estrangulada a golpes de facão",
    "A polícia e a justiça são 2 mãos do mesmo braço",
    "Era servir carne grelhada na ala dos queimados do hospital",
    "Nada sabe melhor que uma mão áspera e grossa",
    "É Cagar para cima de comida à frente de um sem abrigo esfomeado",
    "Salazar",
    "A conta do gás do Hitler",
    "Um longo, brilhante, grosso pénis",
    "Violação consensual",
    "Tamos a precisar duma Limpeza étnica",
    "O meu grande objetivo de vida é um dia ter um corpo para poder Masturbar na casa de banho do museu do Holocausto",
    "Sabes quando coças tanto os tomates que eles ficam em carne viva?",
    "Lars Ulrich é merda 😂😂",
    "Típica rapariga branca",
    "És mau. Vilão. Feioso. Camelo. Pinguim. Cabeça de burro. Urso. Oragotango. Rinoceronte. Palerma. É o que tu és Satan. És tu",
    "Algures no mundo uma árvore esta a trabalhar para substituir o oxigênio que tu desperdiças",
    "Não és a pessoa mais burra do mundo, mas reza para essa pessoa não morrer",
    "Enquanto te ouvia falar, lembrei-me que tenho de deitar fora o lixo",
    "A inteligência é uma virtude não comum a todos",
    "Que os teus dedos se transformem em ganchos e que te dê comichão nos tomates",
    "Haviam de te besuntar com mel e atirar-te aos ursos",
    "Já se questionaram como é que a malta sem braços limpa o cu depois de cagar?",
    "Puta crime namber faive",
    "Diga um"
]
