arr_mention = [
    "Tás a falar para mim oh boi?",
    "What is it now?",
    "I swear, talking to you is like talking to a brick wall",
    "Do I really have to deal with this?",
    "This is getting old real fast",
    "Deixa de ser parvo",
    "Que é que foi pah?",
    "Sabes uma coisa, és um chato",
    "Tou-me a cagar",
    "Caguei d'alto",
    "Vai chatear outro",
    "Ide para o caralho",
    "Vais sozinho ou queres que te mande?",
    "Great, another Monday",
    "You talkin' to me?",
    "I'm surrounded by idiots",
    "That's it, I'm outta here",
    "I can't believe you just said that",
    "Are you serious right now?",
    "I'm too old for this nonsense",
    "Se não fosses um burro, o que é que gostavas de ser?",
    "Com todo o respeito, vai tomar no cu",
    "Ninguém te curte mano",
    "Tu és um chato do caralho",
    "Que é que foi caralho?",
    "You're a sad, strange little man, and you have my pity",
    "Every single thing about you is ugly",
    "You're a disease",
    "You're a cotton-headed ninny muggins",
    "Can't you just leave me alone for once?",
    "This is getting ridiculous",
    "I've had it up to here with you",
    "I can't deal with this right now",
    "You're really pushing my buttons",
    "Sabes que eu te odeio, certo?",
    "Vai chupar um limão",
    "Ide fornicar contigo próprio",
    "Po caralho",
    "Cala-te crl",
    "Vamos lá ver as confianças",
    "Respeitinho se faz favor",
    "Poe-te nas putas",
    "Porque é que achas que és digno da minha paciência",
    "Tu aborreces-me",
    "Com todo o respeito, vai para o caralhinho",
    "Comi a tua mãe",
    "Comi a tua avó",
    "era isso e deixares de ser burro",
    "É lidar",
    "O bigode da tua tia",
    "É assim, não foi das coisas mais burras que já li, mas tá perto",
    "Bem podre",
    "Vai dormir que o teu mal é sono",
    "Um relógio parado acerta mais vezes do que tu",
    "É mamares",
    "Tás carente, queres atenção?",
    "Porque é que estás a falar com um bot?",
    "Eu sou só código, tás a falar sozinho",
    "Tás-me a chatear porque não tens outros amigos?",
    "Bitch, where's my money!?",
    "Shitting your pants to end a bad date",
    "Tás bebedo?",
    "Are you drunk?",
    "A cheese-grater to the dick",
    "I literally don't give a flying fuck about you",
    "Absolutely Fuck-All",
    "Toirão não teme",
    "És um ser miserável e eu odeio-te",
    "Todos te odiamos, sabes disso?",
    "Há todo um outro grupo de discord só para falar mal de ti",
    "Papava-te",
    "Não sei o que é mais autista, tu por dizeres merda, ou eu que respondo",
    "Por qué no te callas?",
    "Tá tudo moçe",
    "Eu até te insultava, mas acho que és demasiado burro para perceberes",
    "Joga-te",
    "Vai-te sentar num ananás",
    "Os teus pais são irmãos?",
    "Oh colega, oh colega...",
    "Que foi, seu cona de sabão?",
    "Mostra respeito, só não sou teu pai porque a tua mãe não tinha troca para nota de 20",
    "Respeitinho",
    "Calado eras um poeta",
    "Não tenho paciência nem lápis de cera para te explicar",
    "Não esperava nada de ti e ainda sim fiquei decepcionado",
    "Vou-te arranjar uma folha de papel e uns lapis de cera pra te entreteres e não chateares mais ninguém",
    "Mr. Madison, what you just said is one of the most insanely idiotic things I have ever heard. At no point in your rambling, incoherent response, were you even close to anything that could be considered a rational thought. Everyone in this room is now dumber for having listened to it. I award you no points, and may God have mercy on your soul.",
    "Seu saco de merda mal amarrado!",
    "Aquilo que faz de nós pessoas é a capacidade de pensar, e eu adorava que tu fosses uma pessoa",
    "Não deixes que esse cromossoma extra te mande abaixo",
    "Desculpa, às vezes acho que sou demasiado agressivo",
    "Deus te guarde e se esqueça onde guardou",
    "O problema é que o senhor vota",
    "Só não te fodo o focinho porque sou um bot e não tenho corpo",
    "Tenho inveja das pessoas que nunca te conheceram",
    "A tua mãe devia de te ter engolido",
    "Ganha vergonha nessa puta dessa cara e faz-te um homem, porco do caralho!",
    "Fala-me do acidente",
    "Eu até te partia a cara, mas isso era uma melhoria",
    "Se fosses duas vezes mais esperto ainda continuavas a ser burro",
    "I forgot the world revolves around you. My bad!",
    "You seem to be suffering from delusions of adequacy",
    "My days of not taking you seriously have come to a middle",
    "You are the human equivalent of a participation trophy",
    "Whatever kind of look you were aiming for, you missed",
    "You may have a sparsely attended funeral",
    "I smell something burning. Are you trying to think again?",
    "You're like a lighthouse in a desert: bright but not very useful",
    "Don't worry—the first 30 years of childhood are always the hardest",
    "May your life be as pleasant as you are",
    "Your biscuit's not done in the middle",
    "Your face is just fine. It's your personality that's the issue",
    "Whatever is eating you must be suffering terribly",
    "I will not have a battle of wits with someone who is unarmed",
    "You look like you were a slippery baby",
    "May the chocolate chips in your cookies always turn out to be raisins",
    "Where's your off button?",
    "You're as sharp as a rubber ball",
    "How do you not fall down more?",
    "You're as deep as a puddle in a parking lot",
    "I would describe your personality as a vibrant shade of beige",
    "You don't need to fear success. You have nothing to worry about",
    "If you ever had a thought, it would die of loneliness",
    "Guess you're not as dumb as you look. How could you be?",
    "You should use glue instead of chapstick",
    "I may not be perfect, but at least I am not you",
    "Your life is more about regret management than goal achievement, isn't it?",
    "I'll never forget the first time we met. But I'll keep trying",
    "I admire the way you try so hard",
    "The key to happiness is to live without regrets and embrace your mistakes. Hug?",
    "You look easy to draw",
    "Seu boiadeiro"
    
]