arr_offerings = [
    "Kali accepts your offerings",
    "You sicken me",
    "Not bad",
    "That is the most creepy sentence I've read so far",
    "I used to hate you. I still hate you, but a bit less now",
    "You thought of that, you're sick man",
    "To infinity and beyond!",
    "Finish him!",
    "All you need is love",
    "That's what she said",
    "Winter is coming",
    "May the Force be with you",
    "Could you be any more annoying?",
    "I literally can't even",
    "I'm surrounded by idiots",
    "This is the grossest thing I've ever seen in my life!",
    "Burn it with fire!",
    "Nope. Just nope",
    "Tell me you're kidding",
    "This ain't it, chief",
    "Cringe!",
    "Oh, honey, no",
    "Delete that from existence!",
    "Oh, valha-me Deus!",
    "Que cena mais reles!",
    "Até a barraca abana",
    "Eu não mereço isto!",
    "Mas que raio foi isto?",
    "Está bem, abelha!",
    "Boa noite, e fiquem bem!",
    "O estado a que isto chegou",
    "Olhe que não, doutor, olhe que não",
    "Prognósticos só no fim do jogo",
    "Por isso sai, sai da minha vida",
    "Bicha do demónio afasta-te!",
    "Chuta daí, caralho!",
    "E o burro sou eu? Pimbolim é Matraquilho",
    "Lá fora está-se pior. Tá-se tá-se. Tá-se.",
    "Sepultar os mortos e cuidar dos vivos",
    "Querem fazer de nós bodes respiratórios",
    "Ponha. Ponha. Ponha",
    "Raramente me engano e nunca tenho dúvidas",
    "O que eu gostava era de escascar pedra",
    "Quando estávamos à beira do abismo, tomámos a decisão certa: demos um passo em frente.",
    "OLÉ, OLÉ, E ESTA MERDA É TODA NOSSA, OLÉ, OLÉ!!!",
    "Falam falam, falam falam, falam falam, mas não os vejo a fazer nada",
    "E foi aqui... exatamente aqui!...",
    "E esta ein?",
    "Façam o favor de ser felizes",
    "Tou cheio de te oubir",
    "Sabes o q é nd desta bida? É nada desta bida!",
    "Chupa Teresa",
    "Em condições normais, seremos campeões. E em condições anormais... também vamos ser campeões",
    "Eu quero que o público português se foda",
    "Por favor, não me chamem arrogante só porque digo a verdade. Mas eu sou campeão europeu e penso que sou especial",
    "Acho que você, o que quer mesmo é dar-me música, mas a mim não me apetece dançar",
    "Eu expalico, você só compalica",
    "Tudo vale a pena quando a alma não é pequena",
    "Mudam-se os tempos, mudam-se as vontades",
    "Basta que um homem odeie outro para que o ódio vá correndo até a humanidade inteira",
    "Aqui ao pé da terra acaba o mar",
    "Se tens um coração de ferro, bom proveito. O meu fizeram-no de carne, e sangra todo dia",
    "É preciso sair da ilha para ver a ilha. Não nos vemos se não sairmos de nós",
    "Os sonhos são como as pessoas: morrem",
    "Escrever é como engolir vidro. Nunca sai incólume",
    "O mundo que não penso é o mundo que me pensa",
    "Deus quer, o homem sonha, a obra nasce",
    "Portugal é um país de bananas governado por sacanas",
    "A sociedade portuguesa era, como dizia o Ega, uma vasta palhaçada",
    "Sabeis, peixes, que vossa virtude é o silêncio?",
    "Os homens, por falta de virtude, perdem o que têm; os peixes, por excesso, perdem-se a si mesmos",
    "Os homens são piores que os peixes, porque não só enganam os pequenos, mas também a si mesmos",
    "O maior pecado dos homens é o esquecimento",
    "Aprendei que todo bajulador vive à custa de quem lhe dá ouvidos",
    "Quem pensa enganar, muitas vezes é enganado",
    "A jornada é longa, mas a glória é eterna",
    "Tudo o que é grandioso exige sacrifício",
    "O que a alma sente é mais forte do que o que a razão pensa",
    "O tempo apaga tudo, até as mais profundas cicatrizes do coração",
    "Happiness can be found, even in the darkest of times, if one only remembers to turn on the light",
    "Honor is dead, but I'll see what I can do",
    "Life before death. Strength before weakness. Journey before destination",
    "The true test of a leader is not what they can do in the light, but how they stand when darkness surrounds them",
    "Despair is like a drug. It numbs you to the pain, but the cost is that it takes away the joy as well",
    "There is some good in this world, Mr. Frodo, and it's worth fighting for",
    "I wish the Ring had never come to me. I wish none of this had happened",
    "You shall not pass!",
    "Do or do not. There is no try",
    "The force is strong with this one",
    "Tu te tornas eternamente responsável por aquilo que cativas",
    "É o tempo que passaste com tua rosa que a faz tão importante",
    "Os adultos nunca entendem nada sozinhos, e as crianças cansa-se de explicar-lhes sempre e sempre",
    "I don't want to be a monster. But I can't change what I am",
    "A lesson without pain is meaningless. That's because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart.",
    "Humankind cannot gain anything without first giving something in return",
    "The only thing we're allowed to do is believe that we won't regret the choice we made",
    "I'm not a hero because I want your approval. I do it because I want to!",
    "I don't believe in God, but I believe in the devil, and the devil's in the details",
    "I'm not a dog, I'm a genius!",
    "We're all just kids in the end",
    "See you space cowboy",
    "Bang",
    "Whatever happens, happens",
    "Que sera sera",
    "I was born in the darkness... but I don't care anymore",
    "My goal is not revenge. It's to regain the eyes of my people",
    "I don't care about money. I care about... the thrill of the fight",
    "A goal without a plan is just a wish",
    "I am not the same as I was before. I understand now. The world is not as simple as I once thought",
    "I have always been a king. But what is a king without people?",
    "If I must die, I will die. I will die as I live—fighting",
    "The human heart is a very fragile thing",
    "I don't fear death. I only fear regret",
    "Pikachu, I choose you!",
    "Prepare for trouble, and make it double!",
    "Gotta catch 'em all!",
    "The Dude abides",
    "I am the walrus",
    "Say 'what' again. I dare you. I double dare you, motherfucker. Say what one more goddamn time!",
    "I'm gonna get medieval on your ass",
    "I am Jack's complete lack of surprise",
    "All those moments will be lost in time, like tears in rain",
    "I've seen things you people wouldn't believe",
    "Inconceivable!",
    "Hello. My name is Inigo Montoya. You killed my father. Prepare to die",
    "There is no spoon",
    "As far as I'm concerned, this is the greatest thing that could ever happen to me",
    "We're all pretty bizarre. Some of us are just better at hiding it, that's all",
    "Nobody puts Baby in a corner",
    "I'm not even supposed to be here today!",
    "Groovy",
    "I hope that when the world comes to an end, I can breathe a sigh of relief, because there will be so much to look forward to",
    "I ate his liver with some fava beans and a nice Chianti",
    "It puts the lotion on its skin or else it gets the hose again",
    "The greatest trick the Devil ever pulled was convincing the world he didn't exist",
    "Are you gonna bark all day, little doggy, or are you gonna bite?",
    "Toto, I've a feeling we're not in Kansas anymore",
    "You talkin' to me?",
    "We're just two lost souls swimming in a fish bowl, year after year",
    "Eu não te amo, nem te odeio, eu sou assim",
    "Não sei se a vida é boa, mas eu sei que a morte é melhor",
    "Não sei quem sou, mas sei que estou aqui",
    "A casa está a arder e a gente a olhar",
    "É uma casa a arder",
    "Eu sou a noite, e a noite é minha",
    "I'm so happy cause today I found my friends, they're in my head",
    "We don't need no education, we don't need no thought control",
    "Is there anybody out there?",
    "You can't always get what you want, but if you try sometime, you find you get what you need",
    "I can't get no satisfaction",
    "Nothing else matters",
    "I have become comfortably numb",
    "Us and them, and after all, we're only ordinary men",
    "The lunatic is on the grass",
    "Hey Jude, don't make it bad. Take a sad song and make it better",
    "And now my life has changed in oh so many ways",
    "There's nothing you can do that can't be done, nothing you can sing that can't be sung",
    "You may say I'm a dreamer, but I'm not the only one",
    "You should have heard the things that came out of her mouth. I thought I was going to puke",
    "You are a liar and a traitor",
    "You are a being of no consequence. I have no time for you.",
    "I am Beyoncé, always",
    "That's repulsive",
    "Refluxei",
    "I can't even look at you right now",
    "Epah reduz-te",
    "Ugh, just... stop",
    "How dare you!",
    "You're completely out of line",
    "Isso é repugnante",
    "Tu não vales nada",
    "Fico enojado só de pensar nisso",
    "Isso é de uma imoralidade tremenda",
    "Senti-me sujo",
    "Eu não me envolvo com esse tipo de coisa",
    "Deu-me calafrios e tudo",
    "És de um mau gosto indescritível",
    "És a minha melhor amiga, e sempre vais ser!",
    "Não tens de ser perfeito, tens de ser verdadeiro",
    "Ai, que isto está a ficar cada vez mais complicado!",
    "Já não sei se isto é sério ou se estou a sonhar!",
    "Eu não sou maluco, só estou a tentar entender o que se passa!",
    "Isto é tudo uma confusão, mas eu gosto assim!",
    "Isso parece que veio dos Morangos com Açucar"
]
