arr_piropo = [
    "Tu não és um ataque de asma, mas quando eu te vejo fico sem ar",
    "Usas cuecas TMN? É que tens um rabinho que é um mimo",
    "Ó flôr dá para pôr? ",
    "Ó musa dás-me tusa",
    "Ó bomboca, mostra a toca?",
    "Ó doce, era onde fosse",
    "Ó beleza, deixas-ma tesa",
    "Ó boneca, vai uma queca?",
    "És como um helicóptero: gira e boa",
    "Ó fêvera, junta-te aqui à brasa",
    "Ó jóia, anda aqui ao ourives",
    "Ó morcona, comia-te o sufixo",
    "Ó filha, aperta aqui que é mais fofo",
    "Ó jeitosa, és mais apertadinha que os rebites de um submarino",
    "Andas na tropa? É que marchavas que era uma maravilha",
    "Tantas curvas e eu sem travões",
    "A tua mãe só pode ser uma ostra para cuspir uma pérola como tu",
    "Tens um cu que parece uma cebola, é de comer e chorar por mais",
    "Só queria que fosses uma pastilha elástica para te comer o dia todo",
    "Tanta carne boa e eu em jejum",
    "Se o teu cu fosse um banco, fazia uma poupança a taxa fixa",
    "Belas pernas, a que horas abrem?",
    "A ti não te custava nada e a mim sabia-me tão bem",
    "Até davas uma boa actriz mas és muito melhor atrás",
    "Ainda dizem que as flores não andam",
    "Ó filha, com um cuzinho desses deves cagar bombons",
    "Ó filha, levavas aí com o martelo pneumático que fazíamos o túnel do Marquês num instante",
    "Que bela anilha que tu tens, deixa lá enroscar o meu parafuso",
    "Só custa a cabeça que o resto é pescoço",
    "Que rica sardinha para o meu gatinho",
    "Anda cá a cima afagar-me a cobra zarolha",
    "Ó filha, o teu pai devia ter a régua torta para te fazer com curvas assim",
    "Queres ir comigo ver ali umas escadas que eu conheço?",
    "Ó filha, fazia-te um pijaminha de cuspo",
    "Quem me dera que fosses um frango para te meter um pau no cu e fazer-te suar",
    "Só queria que fosses um cavalinho de carrossel, para te montar todo o dia por 50 cêntimos",
    "Ó filha, anda cá a cima que até a barraca abana",
    "Contigo filha, era até ao osso",
    "Metia-te-a inteira até que ma mordesses",
    "Posso tocar no teu umbigo da parte de dentro?",
    "Ai de ti que eu saiba que esse cuzinho anda a passar fome",
    "Só não tenho pêlos na língua porque tu não deixas",
    "Ó filha, anda cá a cima que ele não se vai chupar sozinho",
    "Tens uns olhos tão lindos, tão lindos, que te comia essa peida toda",
    "Contigo era até encontrar petróleo",
    "Ó linda, sobe aqui à palmeira e anda-me lamber os cocos",
    "Ó faneca, anda cá que o pai unta-te",
    "O teu cu parece uma serra eléctrica, não há pau que lhe resista",
    "És tão quente que até se me grelham os tomates",
    "O meu amor por ti é como a diarreia, não o consigo manter cá dentro",
    "Diz-me quem é o teu ginecologista para eu lhe ir chupar o dedo",
    "Com esse cu, estás convidada a cagar na minha casa",
    "Contigo até me tornava mineiro, só para te abrir os buracos todos",
    "Podia ficar um mês a cagar trapos mas comia-te com roupa e tudo",
    "Posso pagar-te uma bebida ou preferes em dinheiro?",
    "Ainda dizem que a fruta verde não se come",
    "Ó filha, lambia-te o que tu mais gostas",
    "Ó fofa, agarra aqui na corneta",
    "Agarra-me aqui no tarolo, ó princesa",
    "O teu pai deve ser arquitecto, tens um cu que é uma obra",
    "Ó filha, agarra aqui com a mão",
    "Que rico filho. Anda cá cima que eu faço-te outro mas mais bonito",
    "Ó boneca, era a estrear",
    "Ia até ao fim do mundo por um dos teus sorrisos, e ainda mais longe pela outra coisa que podes fazer com a boca",
    "Estou a lutar desesperadamente contra o impulso de fazer de ti a mulher mais feliz do mundo",
    "Sabes onde ficava bem a tua roupa? Toda amarrotada no chão do meu quarto",
    "Só a mim é que não me calha uma destas na rifa",
    "Diz-me lá como te chamas para te pedir ao Menino Jesus",
    "Ó filha, queres ir ao céu? Vem ter comigo que o resto do caminho é por minha conta",
    "Ó filha, se não acreditas que Deus é feito de 0s e 1s anda cá tocar-me",
    "Abençoados pais que conceberam esta coisinha linda",
    "Por acaso és católica? É que tens um cu que valha-me Deus",
    "Se eu estivesse no teu lugar, tinha sexo comigo na boa",
    "Essa roupa fica-te muito bem, mas eu ficava-te melhor",
    "Se cair, já sei onde me agarrar",
    "Acreditas em amor à primeira vista ou tenho que passar por aqui outra vez?",
    "Anda cá que te vou dar uma sessão de raboterapia",
    "Não sou muito bom em matemática mas, 1+1 = 69?",
    "Não te esqueças do meu nome, mais logo vais gritá-lo",
    "És um bilhete de primeira classe para o pecado",
    "Queria ser um patinho de borracha para passar o dia na tua banheira",
    "Deves estar tão cansada, passaste a noite às voltas na minha cabeça",
    "Posso não ser bonito como o Brad Pitt, nem ter os músculos do Schwarzenegger, mas a lamber sou uma Lassie",
    "Com uma montra dessas, imagino como é o armazém",
    "Ó filha, contigo era até partir os pés à cama",
    "Ó doce, anda cá a cima fazer uma festinha ao tareco",
    "Não és nada de se deitar fora, já tive pior e a pagar",
    "Podes não ser a pessoa mais gira, mas com a luz apagada também é bom",
    "Ó filha, tens carinha de modelo mas o teu cu é um continente",
    "Com umas bóias dessas o Titanic não tinha ido ao fundo",
    "Com um piso desses deves ser mais rodada que a 2ª Circular",
    "Ó filha, se o teu cu fosse uma torrada, precisava de um remo para o barrar"
]