arr_roast = [
    "Tu não és estúpido, tens é azar quando pensas.",
    "Devias andar com o colete reflector vestido. A tua cara parece que está em obras",
    "O teu certificado de nascimento é um pedido de desculpas da Durex",
    "A tua mãe é como o Pingo Doce, sabe bem pagar tão pouco",
    "A tua mãe é tão gorda que quando passa à frente da TV perdes 3 temporadas",
    "A tua mãe é como uma lareira, cabe sempre mais um pau",
    "A tua mãe é como o Continente: ontem, hoje e amanhã",
    "Tu justificas o aborto retroactivo",
    "A tua mãe devia ter engolido",
    "Tens uma cara boa para rádio",
    "Se a beleza pagasse imposto, tu estavas isento desde o nascimento",
    "O teu contraceptivo é a tua cara",
    "A tua cara faz as cebolas chorar",
    "Trocado por merda ainda dás prejuízo",
    "Aposto que quando perguntam por ti aos teus pais eles mudam de assunto",
    "A única cultura que tens é de bactérias",
    "Tens mais cornos que uma travessa de caracóis",
    "Se tivesse a tua cara, metia os meus pais em tribunal",
    "Se algum dia te quiseres matar salta do teu ego para o teu QI",
    "Devias emagrecer para haver menos de ti no mundo",
    "Se merda fosse ouro tu eras um tesouro",
    "Quando nasceste eras tão feio que o médico deu-te uma chapada na cara e te meteu a chupeta no cú",
    "És a inspiração para o controlo de natalidade",
    "Se fosses duas vezes mais esperto ainda continuavas a ser burro",
    "Aposto que quando cagas tens que assobiar para não te esqueceres que buraco limpar",
    "É impossível substimar-te",
    "Cheiras a puré",
    "És tão feio que quando trincas o limão, o limão é que faz caretas",
    "O teu QI está no topo da distribuição normal",
    "Tu és daqueles que chumba nos testes de QI",
    "O teu QI está no topo da distribuição normal",
    "Nem Jesus te amava se tivesse de conviver contigo",
    "Para te mascarares de palhaço só precisavas de pendurar uns elásticos nas orelhas",
    "És mais inútil que um lápis de cor branco",
    "Sorry, I can't think of an insult dumb enough for you to understand",
    "Tiveram que tapar a incubadora para convencer os teus pais a levar-te",
    "You're so annoying, you could make a Happy Meal cry",
    "You are even more useless than the 'ueue' in queue",
    "You're the reason they put directions on shampoo bottles",
    "When I see you coming, I get pre-annoyed. I figure it's smart to give myself a head start",
    "You are like a software update. Every time I see you, I immediately think 'not now'",
    "Give me a minute, I'm trying to think of an insult simple enough for you to understand",
    "When I look at you, I think to myself where have you been my whole life? And can you go back there?",
    "You are the human version of cramps",
    "You're like a cloud. When you disappear, it suddenly becomes a beautiful day",
    "You look like something that came out of a slow cooker",
    "I was going to roast you, but apparently, burning trash is an environmental hazard",
    "It's the parent's job to raise their children right. So looking at you, it's obvious that they quit after just one day",
    "A tua cara",
    "Tens cara de quem tenta engatar pitas nos carrinhos de choque",
    "Com todo respeito, vai tomar no cu",
    "Tens o aspecto de quem lava a cara com o cozido à portuguesa",
    "Tens cara de quem perdeu a virgindade com um presunto",
    "Na tua presença a palavra 'Higiene' é sempre sarcasmo",
    "Tens cara de que em puto sustiveste a respiração demasiada vezes",
    "Nos debates a favor do aborto, deviam usar usar a tua fotografia como argumento",
    "A tua cara parece que foi feita de memória por um caricaturista que vê mal ao perto",
    "Tens cara de quem nunca panou de luz acesa",
    "Se a inteligência fosse dinheiro, tu estavas a dever até ao próximo século!",
    "A tua capacidade de concentração é tão fraca que até o café desiste de te manter acordado!",
    "Tens cara de quem precisa do Google Maps para te orientares na tua própria casa",
    "Se a burrice desse prémios, tu já tinhas conquistado o Nobel",
    "Até a tua sombra tem vergonha de te seguir",
    "A tua falta de talento é tão evidente que até o teu talento em ser inútil é questionável",
    "Se a asneira fosse um superpoder, tu serias um super-herói",
    "A tua criatividade é tão limitada que até os pintores de paredes te superam",
    "Se a incompetência fosse música, tu serias um hit mundial",
    "Se o falhanço fosse uma arte, tu serias um Picasso",
    "Se o mau gosto fosse uma doença, tu estavas em estado terminal",
    "A tua vida amorosa é tão ativa como uma tartaruga em hibernação",
    "You're about as useful as a screen door on a submarine",
    "If you were a spice, you’d be flour",
    "You’re just like a Russian doll—full of yourself",
    "You have the attention span of an ice cream in July",
    "You are proof that the universe has a sense of humor",
    "I bet your pH level is 14. Basic",
    "I’m not saying you’re ugly, but maybe you should start walking backward",
    "I bet you take more than 15 items through the express lane",
    "You have the charisma of a wet sock",
    "You look like you’d struggle to pour water out of a boot with instructions on the heel",
    "My life may be a joke, but it’s not as funny as your face",
]
