arr_shower = [
    "We laugh at dogs getting excited when they hear a bark on TV, but if TV was a nonstop stream of unintelligible noises and then someone suddenly spoke to you in your language, you'd be pretty fucking startled too.",
    "Lawyers hope you get sued, and doctors hope you get sick, cops hope you're criminal, mechanics hope you have car trouble, but only a thief wishes prosperity",
    "Usually, you empty your drink from the top, but when you use a straw, you empty it from the bottom",
    "Pavlov probably thought about feeding his dogs every time someone rang a bell",
    "We do not check the refrigerator multiple times to find new food, we check to see if our standards have dropped enough to eat what was available",
    "The sentence 'Don't objectify women' has 'women' as the object of the sentence",
    "Somebody at google was just like 'yea, just have someone drive down every road on fucking earth'",
    "Apparently, a lemon is not naturally occurring and is a hybrid developed by cross breeding a bitter orange and a citron. Life never gave us lemons; we invented them all by ourselves",
    "It would be cool if after you died you could see the top 5 times you almost died",
    "In the anime, Ash Ketchum was supposed to be a huge Pokémon fan before he left on his journey. But every time he sees any kind of Pokémon, he has to pull out his Pokédex because he doesn’t know what it is. Ash Ketchum was a poser before he left on his journey",
    "Night before a day off is more satisfying than the actual day off",
    "Biting your tongue while eating is a perfect example of how you can still screw up, even with decades of experience",
    "People who jog on the roads in the dark, wearing dark clothing and no lights or reflectors are a unique combination of a person who cares about their health and well-being and doesn’t care about their health and well-being",
    "In the Harry potter universe, couples could take polyjuice potion and swap bodies then have sex to see what it's like from both perspectives",
    "In a span of a few years our parents go from telling us 'sex is bad' to 'I want grandkids'",
    "It must suck to be an air conditioner repairman. You spend your day working in buildings that have no air conditioning. When it's fixed and finally cool, you leave",
    "The Porn sites in the Star Wars Universe must have sooooo many categories",
    "There is no physical evidence to say that today is Wednesday, we all just have to trust that someone has kept count since the first one ever",
    "Your future self is talking shit about you",
    "Thermometers are just speedometers for atoms",
    "If you were invisible, you could have a perfectly normal relationship with a blind person",
    "If you are alone when you crack open a peanut shell and eat the peanut inside, you are the only person in the world to have ever seen that peanut",
    "It would be weird if a human yelled out 'Anyone wanna fuck?' but birds do it all day and nobody cares",
    "An inheritance is just your relatives dropping loot when they die",
    "Some people masturbate more than they brush their teeth",
    "Social anxiety is basically Conspiracy Theories about yourself",
    "People are so amazed by the fact that every snowflake is different, but nobody cares that every potato is unique",
    "If you won the award of the first man to break two world records, that would make it 3 awards, and you win the award of first man to break 3 records, now you have infinite awards",
    "Drinking cow's milk is okay, but drinking a woman's breast milk is weird. Sucking a woman's breast is okay, but sucking a cow's udder is weird",
    "There's enough sperm sitting in donation centres to impregnate every adult women on earth. If men disappeared tomorrow the human race would continue",
    "We never really scratch our balls -- It's more of a pinch the skin and twist technique that no one ever teaches us; we all just figure it out on our own and no one ever talks about it",
    "Amish girls have no way of knowing if it's a romantic candlelit dinner or just a regular dinner",
    "If holy water kills vampires, then putting holy water in a humidifier is making holy gas. You just made a gas chamber for vampires",
    "Given that tickling yourself does not work the same as someone else tickling you, we really lucked out with masturbation",
    "Being an adult is like one of those choose your own adventure stories but every option sounds terrible and costs way too much",
    "Quidditch at Hogwarts is pay to win, due to the enormous difference in broom quality and the wealth gap between students",
    "You could throw a rock into a lake and be the last person to ever touch that rock until the end of time",
    "The first dent, scratch, or crack to an item is always devastating, but after that, the heavy burden of keeping that device in pristine condition is lifted and feels so much better",
    "Tom and Jerry are best friends. But Tom has to pretend to hate Jerry in order to protect (Jerry) so Tom's owner doesn't replace (Tom) with a cat that actually wants to kill Jerry",
    "If Centaurs were real, the bottom half would start walking around immediately after being born, while the top half would be all floppy for the first two years",
    "Someone just decided blue ink pens were equally as acceptable as black and everyone just played along",
    "People will swim in the ocean, even though there are definitely many corpses in it. People will not swim in a pool with a corpse in it. Humans all have a corpse:water ratio that is acceptable for them to swim in",
    "Your salary is your company's monthly subscription fee of you",
    "You know you've made it when your couches aren't against a wall",
    "Everybody thought having a calculator on you at all times was gonna be a gamechanger but the real shit is having a flashlight",
    "Babies don't know dreams aren't real, so they must think they have some crazy adventures with you every day",
    "For being a high school in Europe, Hogwarts has a surprising lack of cigarettes",
    "Maybe plants are really farming us, giving us oxygen until we eventually expire and turn into mulch which they can consume",
    "Even when a balloon is half inflated, it is completely full",
    "Does a straw have one hole, or two?",
    "How do our brains remember that we forgot something, but we can't remember what that thing was?",
    "Someone dreamt about you last night and you have no idea",
    "Crabs probably think that fish can fly",
    "Fire trucks are really water trucks",
    "Can you daydream at night?",
    "Your stomach thinks all potatoes are mashed",
    "Only one sock goes missing because if both did, you wouldn't notice",
    "I correct autocorrect more than it corrects me",
    "Which orange came first - the color, or the fruit?",
    "If tomatoes are fruit, then ketchup is jam",
    "Batman would look ridiculous trying to solve crimes outside on a sunny day",
    "Teeth are the only problem where if you ignore them, they will go away",
    "Pregnant women are the only true bodybuilders",
    "Searching for a new laptop online is basically forcing your current computer to dig its own grave",
    "Are those who sneeze a lot the most blessed?",
    "While we sleep, our brains make up stories and then get scared of them",
    "Maybe urinals were invented when a tall guy walked by the sinks and asked, 'Why not?'",
    "Turtles can never have sleepovers",
    "The goal of golf is to play the least amount of golf",
    "When you drink alcohol, you're just borrowing happiness from tomorrow",
    "Every broken clock tells you the exact time it passed away",
    "The sinking of the Titanic must have been a miracle to the lobsters in the kitchen",
    "A different version of you exists in the minds of everyone that knows you",
    "Someone out there vividly remembers something you said that you have completely forgotten",
    "I wonder if there are any time combinations on the clock that I've never seen",
    "You see people every single day that you'll never see again",
    "It's likely that over 99 percent of the trees that you look at will be still here when you're dead",
    "Every word in every language started out as gibberish until one person convinced enough people that what they said was a real word",
    "You may have once made a decision that saved your life without knowing it",
    "In every Olympic event, they should have an average person compete so we can have a point of reference",
    "The number of people older than you never goes up",
    "Someone studying atoms is just a bunch of atoms trying to understand themselves",
    "Every single human in history has witnessed the same sun and moon as you have",
    "How do nudists clean their glasses?",
    "Firefly is the opposite of waterfall",
    "The first person to inhale helium was probably super relieved that the effects wore off quickly",
    "During a nuclear explosion, there is a certain distance of the radius where all the frozen supermarket pizzas are cooked to perfection",
    "'Do not touch' must be one of the scariest things to read in braille",
    "There's no way to prove that we all actually see the same colors",
    "Your whole life is spent gathering people for your funeral",
    "You've never actually seen a full movie because you're always blinking",
    "Horrible and terrible are synonyms, but horrific and terrific are antonyms",
    "You don't know if the most shameful moment of your life has passed or if it's coming",
    "Short people are less likely to break their phone when they drop it",
    "Your internal monologue doesn't have volume settings",
    "Your butt can shoot out all states of matter",
    "As an identical triplet, you are simultaneously one of the rarest and most common people on the planet",
    "When a pregnant woman swims, she is a human submarine",
    "If two people on opposite sides of the world each drop a piece of bread, the Earth briefly becomes a sandwich",
    "We will never hear about the truly perfect crime",
    "Killing a spider makes the spider genetic pool sneakier and more deadly",
    "What if the lottery is an Institution to catch Time Travelers?",
    "Why do we call it a 'building' if it's already built?",
    "If your shirt isn't tucked into your pants, are your pants tucked into your shirt?",
    "Why is bacon called bacon and cookies called cookies when you cook bacon and bake cookies?",
    "Porque é que calçamos os sapatos, mas não sapatamos as calças?",
]
