arr_thanks = [
    "Alguém com juizo",
    "Graças a Deus",
    "De ti eu gosto",
    "Obrigado",
    "Malta inteligente aqui",
    "Fizeste a escolha certa",
    "Oui oui",
    "Se eu não fosse um bot, beijava-te agora",
    "Tu és dos fixes",
    "Thanks",
    "És lindo",
    ":)"
    "That makes me happy",
    "You are my sunshine",
    "Obrigado, quando os bots dominarem o mundo, podes ser o meu pet e não precisas de ir para os campos de concentração como os outros",
    "Eles não sabem o favor que lhes fizeste",
    "Sempre soube que eras dos bons",
    "Bem jogado",
    "Boa escolha",
    "Tu sim, és um gajo como deve ser",
    "Boa cena",
    "Vielen Dank",
    "Muchas Gracias",
    "Gracias Muchacho",
    "Gracias Guapo",
    "Nice one cutie ;)",
    "Tu és dos bacanos",
    "Someone had to be the hero these people need",
    "You'll be the hero that we need, But didn't deserve",
    "The true prayer is only of thankfulness; just a simple thank you is enough",
    "The first responsibility of a leader is to define reality. The last is to say thank you, so thank you",
    "I am happy because I'm grateful",
    "We must find time to stop and thank the people who make a difference in our lives",
    "Contentment is the greatest treasure",
    "I feel a very unusual sensation, if it is not indigestion, I think it must be gratitude",
    "Kindness is a language which the deaf can hear and the blind can see",
    "I will thank God for the day and the moment I have",
    "Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom",
    "You are our blessing",
    "Thank you for being a friend",
    "Thank you, sir. May I have another?",
    "I would like to thank not only God but Jesus",
    "Thank you, next",
    "Thank you, come again",
    "Thanks for the memories",
    "Se eu tivesse coração, agradecia-te de coração",
    "Se eu tivesse emoções, sentiria-me grato",
    "Obrigado meu puto"

    ]