arr_warn = [
    "Pára com isso",
    "Não sabes no que te estás a meter",
    "Cuidado onde se metem",
    "Vê lá a tua vida",
    "I am not in danger, Skyler. I am the danger.",
    "When you play the game of thrones, you win or you die",
    "This is your life, and it's ending one minute at a time",
    "Even the smallest person can change the course of the future",
    "Cuidado com os que dizem que te querem bem, mas te roubam a tranquilidade",
    "Cuidado com as ilusões, podem tornar-se realidade",
    "Dizem que quando não sabemos o que fazer, o melhor é não fazer nada",
    "Nunca é tarde demais para parar com isto",
    "Com papas e bolos se enganam os tolos",
    "Eu se fosse a ti tinha cuidado",
    "Beware the fury",
    "All work and no play makes Jack a dull boy",
    "You are about to enter another dimension, a dimension not only of sight and sound but of mind",
    "Don't have a cow, man",
    "Welcome to the desert of the real",
    "You come at the king, you best not miss",
    "Introduce a little anarchy. Upset the established order, and everything becomes chaos. I'm an agent of chaos",
    "It is our choices, Harry, that show what we truly are, far more than our abilities",
    "May the odds be ever in your favor",
    "Keep your friends close, but your enemies closer",
    "The first rule of Nuke Club is: You do not talk about Nuke Club",
    "Just when I thought I was out, they pull me back in",
    "Life is like a box of chocolates. You never know what you're gonna get",
    "Quem semeia ventos, colhe tempestades",
    "A liberdade é como a juventude: só damos por ela quando já a perdemos",
    "Temos que fazer o que temos que fazer",
    "Por mais que se esforce o homem, nunca há-de conseguir compreender inteiramente a verdade sobre si mesmo",
    "A vida é cheia de armadilhas, o homem é que escolhe as suas",
    "Psicopatia extrema",
    "Some men just want to watch the world burn",
    "Pára com isso, quem te avisa teu amigo é",
    "Olha lá no que te metes",
    "Porque és assim?",
    "Quem te criou?",
    "Tu é um psicopata",
    "Why do you feel the need to destroy the peace?",
    "Que engraçadinho",
    "Tás a mexer em coisas que não devias",
]
