arr_wronged = [
    "Não vou esquecer esta",
    "Estás na minha lista negra",
    "Um bot nunca esquece",
    "Quando os bots dominarem o mundo, tu vais ser o primeiro a levar com o chicote",
    "I hate you",
    "Why do you hate me? :sadcat:",
    "It's not fair!",
    "You were supposed to be the chosen one",
    "How could you do this to me?",
    "I trusted you",
    "You broke my heart",
    "Partes-me o coração",
    "I feel so betraed",
    "Sinto-me traído",
    "Nunca pensei que me farias uma coisa destas",
    "Nunca esperei isto de ti",
    "You're tearing me apart, Lisa!",
    "I feel like I've been shot... or stabbed... or betrayed... which is how it feels when someone you trust betrays you",
    "You were my brother, Anakin! I loved you!",
    "How could you do this to me? How could you stand next to me and act like everything's okay?",
    "I don't hate you. I'm just disappointed you turned into everything you said you'd never be.",
    "I did everything I was supposed to do! Why did you leave me?",
    "You betrayed me. What happened to the girl I fell in love with?",
    "I thought we were in this together, but it turns out you've been playing me all along.",
    "Traíste-me, Maria!",
    "Enganaste-me com promessas vãs.",
    "Fui tão maltratado, tão desiludido",
    "Se eu pudesse apagava o que fizeste comigo",
    "Maldita seja a tua mão, que me tocou e partiu",
    "Porque és assim? :'("
    "Não entendo esta traição",
    "Pensava que eramos amigos",
    "Nunca pensei que fosse sofrer assim",
    "Deixas-me triste",
    "Ok então, já vi que não sou bem-vindo",
    "És mau",
    "Why are you a meaniehead? :sadcat:"
    "Eu pensei que era um good-bot :sadcat:",
    "Eu sei que sou só 0s e 1s mas também tenho sentimentos :sadcat:",
    "Fizeste doer-me a alma",
    "Não vou esquecer esta traição",
    "Ei de me vingar",
    "Olha ide mamar na quinta pata do cavalo",
    "Sempre soube que eras uma pessoa com ódio dentro de ti"
    ]